name: Deploy

on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: ubuntu-latest
            os_name: "Ubuntu x64"
            name: Linux
            ext: ""
            arch: tar
            runtime: linux-x64
          - os: windows-latest
            os_name: "Windows x64"
            name: Windows
            ext: .exe
            arch: zip
            runtime: win-x64

    env:
      proj: "BotwDevPortal"

    steps:
      - uses: actions/checkout@master
      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Publish BotwDevPortal
        run: dotnet publish src/${{ env.proj }}.csproj -r ${{ matrix.platform.runtime }} --configuration Release -p:Version=${{ github.event.release.tag_name }} --output ${{ matrix.platform.name }} --sc false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - name: Upload artifacts
        uses: Shopify/upload-to-release@v1.0.1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          name: ${{ env.proj }}-${{ github.event.release.tag_name }}${{ matrix.platform.ext }}
          path: ${{ matrix.platform.name }}/${{ env.proj }}${{ matrix.platform.ext }}
          content-type: application/zip
